services:
  mysql:
    image: mysql
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/biblioteca3.sql:/docker-entrypoint-initdb.d/biblioteca3.sql
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  spring-app:
    build: .
    container_name: spring_app_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/biblioteca
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_ADDRESS: 0.0.0.0
    ports:
     - "80:80"
    volumes:
      - ./src/main/resources/static:/app/static
    networks:
      - app-net
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:

networks:
  app-net: