version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/biblioteca3.sql:/docker-entrypoint-initdb.d/biblioteca3.sql
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  spring-app:
    build: .
    container_name: spring_app_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/biblioteca
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_ADDRESS: 0.0.0.0
    ports: 
      - "8080:8080"
    volumes:
      - ./src/main/resources/static:/app/static
    networks:
      - app-net
    depends_on:
      mysql:
        condition: service_healthy

  apache:
    image: httpd:2.4
    container_name: apache_container
    ports:
      - "80:80"
    networks:
      - app-net
    command: |
      /bin/bash -c "
      # 1. Habilitar módulos requeridos
      echo 'LoadModule proxy_module modules/mod_proxy.so' >> /usr/local/apache2/conf/httpd.conf
      echo 'LoadModule proxy_http_module modules/mod_proxy_http.so' >> /usr/local/apache2/conf/httpd.conf
      echo 'LoadModule rewrite_module modules/mod_rewrite.so' >> /usr/local/apache2/conf/httpd.conf

      # 2. Deshabilitar DocumentRoot y eliminar archivo de bienvenida
      sed -i 's|^DocumentRoot "/usr/local/apache2/htdocs"|#DocumentRoot deshabilitado|' /usr/local/apache2/conf/httpd.conf
      sed -i 's|^<Directory "/usr/local/apache2/htdocs">|#<Directory deshabilitado>|' /usr/local/apache2/conf/httpd.conf
      rm -f /usr/local/apache2/htdocs/index.html

      # 3. Configurar VirtualHost para redirigir TODO el tráfico a Spring
      echo '
      <VirtualHost *:80>
        ProxyPreserveHost On
        ProxyPass / http://spring-app:8080/
        ProxyPassReverse / http://spring-app:8080/

        # Redirección de raíz a /index
        RewriteEngine On
        RewriteRule ^/$ /index [R=302,L]
      </VirtualHost>
      ' > /usr/local/apache2/conf/extra/proxy.conf

      # 4. Incluir configuración del proxy
      echo 'Include conf/extra/proxy.conf' >> /usr/local/apache2/conf/httpd.conf

      # 5. Iniciar Apache
      exec httpd -DFOREGROUND
      "
    depends_on:
      - spring-app

volumes:
  mysql_data:

networks:
  app-net:

